apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::175683351188:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TGBXA9C8U5MJ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::175683351188:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-19T11:51:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1507"
  uid: 5c876a85-d18f-4415-b691-92cb76ca8ceb
